# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
# CODE HERE

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [82]:
# CODE HERE

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [83]:
# CODE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [84]:
# CODE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [86]:
# CODE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [87]:
# CODE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])

### 7. Return the right-hand column of tensor x

In [88]:
# CODE HERE

tensor([[4],
        [4],
        [1]])

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [89]:
# CODE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [105]:
# CODE HERE

tensor([[2, 1, 4],
        [1, 3, 1]])

### 10. Find the matrix product of x and y

In [106]:
# CODE HERE

tensor([[10, 15, 16],
        [ 8, 14, 12],
        [ 9,  7, 17]])
torch.Size([3, 2])
torch.Size([2, 3])
