# Exercise

In [1]:
import numpy as np

1). <code>np.array([True, 1, 2]) + np.array([3, 4, False]) == which one?
    a. np.array([True, 1, 2, 3, 4, False])
    b. np.array([4, 3, 0]) + np.array([0, 2, 2])
    c. np.array([1, 1, 2]) + np.array([3, 4, -1])
    d. np.array([0, 1, 2, 3, 4, 5])</code>
    
2). Create a 2d array with 1 on the border and 0 inside

3). somehow, your $y$ comes in 2D, as we know, in scikit learn, it needs a 1D $y$, in the shape of <code>(samples, )</code>.  Convert this $y$ into 1D
<code>y = np.array([[3, 2, 3, 4, 5]])</code>

4).Given the following array
<code>celsius_fahrenheit = np.array([10, 50, 15, 59, 5, 42])</code>.  Convert them to a 2d array with first col as celsius and second col as fahrenheit

5). Given the 3D temperature field and 1-D pressure coordinates below, calculate: $$T\exp(P/1000)$$ You will need to use broadcasting to make the arrays compatible.

<code>pressure = np.array([1000, 850, 500, 300])
temps = np.linspace(20, 30, 24).reshape(4, 3, 2)
print(temps.shape)</code>

6). Given following arrays: 

<code>array3d = np.array([[[ 0,  1,  2],
                     [ 3,  4,  5],
                     [ 6,  7,  8]],
                    [[ 9, 10, 11],
                     [12, 13, 14],
                     [15, 16, 17]],
                    [[18, 19, 20],
                     [21, 22, 23],
                     [24, 25, 26]]])
</code>
                      
Index into the 3d array to produce the followings 4 arrays

<code>array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])
array([[ 3,  4,  5],
       [12, 13, 14]])
array([2, 5])
array([[11, 10,  9],
       [14, 13, 12],
       [17, 16, 15]])
</code>

7).  Given the following arrays:

<code>#unit is power measured in volts (value is mock)
eeg1 = np.array([[1, 19, 3], [3, 2, 10], [30, 2, 8]])
marker1 = np.array(1)  #cat
eeg2 = np.array([[3, 6, 9], [8, 2, 3], [4, 5, 9]])
marker2 = np.array(2) #dog
eeg3 = np.array([[1, 2, 10], [15, 2, 3], [6, 2, 1]])
marker3 = np.array(1)  #cat
all_eeg = []
all_eeg.append([eeg1, marker1])
all_eeg.append([eeg2, marker2])
all_eeg.append([eeg3, marker3])
all_eeg_numpy = np.array(all_eeg)
print("All eeg numpy: ", all_eeg_numpy)
print("All eeg numpy shape: ", all_eeg_numpy.shape)
</code>

Compare whether marker of 1 (i.e., cat) has an average power higher than 2 across all channels (i.e., dog). Use all_eeg_numpy, assuming that eeg and marker are not given.

Hint: First you want to get eeg belonging to only 1 and 2.  Then perform np.mean across all eeg signals sharing same markers, then np mean across all channels, i.e., column wise.

8). let $x$ be 111 points from 1 to 100, and y be $f(x)$ of $sin$, $cos$, $exp$ and $log$.  Construct $x$ and $y$.  Then use the following function to plot $x$, and $y$

<code>import matplotlib as plt
plt.plot(x,y )
plt.title("Any title",fontsize=16)</code>

9). Let's compute distance between all pairs of X, Y, total of 10 points:

<code>coordinates = np.random.rand(10, 2)
X, Y = coordinates[:, 0], coordinates[:, 1]
import matplotlib.pyplot as plt
plt.scatter(X, Y, s=100)</code>

Then, find the closest neighbor for the fourth points (index 3)

# Solution