# Solution Numpy // Beau
### === Task 1 ===
1. Declare a list of 1 to 4 using range()

2. Continuing, create numpy array from this list, with dtype='float32'

3. Create an numpy array of size 3 by 5 using np.zeros

4. Create an numpy array of size 2 by 3 with filled value 1 / 3

5. Create a list of 500 numbers for 0 to 10

In [2]:
#====== 1 =======
l = [elem for elem in range(1,5)]
print("Answer Q1: ", l)
#====== 2 =======
import numpy as np
n = np.array(l)
print("Answer Q2: ",n)
#====== 3 =======
n_0 = np.zeros((3,5))
print("Answer Q3: ",n_0)
#====== 4 =======
n_f = np.full((2,3),1/3)
print("Answer Q4: ",n_f )
#====== 5 =======
l5 = list(np.random.randint(0,10,(500)))
print("Answer Q5: ",l5 )

Answer Q1:  [1, 2, 3, 4]
Answer Q2:  [1 2 3 4]
Answer Q3:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Answer Q4:  [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Answer Q5:  [9, 3, 5, 4, 1, 3, 3, 2, 9, 0, 1, 9, 5, 4, 0, 8, 8, 7, 2, 9, 2, 9, 1, 0, 9, 8, 2, 5, 3, 0, 5, 7, 4, 8, 9, 9, 8, 2, 2, 0, 2, 2, 8, 1, 8, 6, 7, 8, 7, 3, 5, 0, 1, 8, 4, 6, 2, 2, 4, 5, 5, 6, 5, 8, 3, 1, 2, 0, 7, 3, 7, 8, 9, 9, 3, 1, 9, 8, 0, 6, 5, 1, 7, 6, 1, 2, 3, 2, 5, 7, 6, 1, 9, 4, 7, 8, 2, 8, 9, 2, 8, 1, 1, 9, 5, 3, 7, 2, 1, 8, 9, 1, 9, 3, 0, 7, 6, 6, 3, 8, 9, 2, 5, 7, 6, 8, 2, 7, 3, 2, 2, 1, 2, 3, 6, 5, 9, 7, 2, 3, 9, 0, 2, 4, 9, 5, 9, 6, 5, 0, 2, 9, 4, 8, 5, 9, 4, 9, 7, 8, 5, 1, 2, 3, 7, 3, 1, 8, 6, 1, 4, 4, 9, 2, 0, 3, 8, 3, 6, 0, 0, 6, 4, 9, 9, 9, 8, 3, 8, 3, 5, 9, 2, 5, 4, 5, 9, 1, 0, 9, 7, 5, 1, 3, 2, 7, 9, 4, 4, 5, 2, 6, 8, 5, 0, 9, 4, 0, 6, 0, 7, 6, 2, 7, 4, 4, 0, 0, 8, 5, 9, 3, 6, 5, 4, 8, 2, 6, 7, 1, 6, 9, 8, 3, 5, 9, 0, 3, 1, 4, 0, 3, 5, 1, 1, 5, 5, 4, 1, 6, 0, 4, 9,

6. Create a list of number for 0.001, 0.01, 0.1, 1 using np.logspace

7. Create a diagonal matrix of list [1, 2, 3, 4]

8. Create a random array of size 4 by 5 all filled with random values between 0 and 1

9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5

10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5

11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution

12. Create an identity matrix of size 5 by 5

In [5]:
#====== 6 =======
n6 = np.logspace(-3,0,4)
print("Answer Q6: \n",n6 )
#====== 7 =======
n7 = np.diag(list(range(1,5)))
print("Answer Q7: \n ",n7 )
#====== 8 =======
n8 = np.random.random((4,5))
print("Answer Q8: \n ",n8 )
#====== 9 =======
n9 = np.random.randint(2,5,(4,5))
print("Answer Q9: \n ",n9 )
#====== 10 =======
n10 = np.random.uniform(2,5,(4,5))
print("Answer Q10: \n ",n10 )
#====== 11 =======
n11 = np.random.normal(5,1,(4,5))
print("Answer Q11: \n ",n11 )
#====== 12 =======
n12 = np.identity(5)
print("Answer Q12: \n ",n12 )

Answer Q6: 
 [0.001 0.01  0.1   1.   ]
Answer Q7: 
  [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Answer Q8: 
  [[0.48702442 0.21792889 0.53522703 0.82130149 0.27047085]
 [0.3156344  0.33593365 0.71930301 0.7364491  0.40750944]
 [0.56587019 0.03011415 0.29037151 0.17974681 0.13533175]
 [0.86559947 0.0740052  0.35514045 0.35638137 0.97446543]]
Answer Q9: 
  [[4 4 3 2 3]
 [3 2 4 3 4]
 [3 3 4 3 2]
 [2 2 3 2 2]]
Answer Q10: 
  [[4.33534596 4.48598009 3.76779916 3.48314174 4.72122943]
 [2.30253859 3.45980201 2.03363397 3.15542069 2.93435202]
 [2.92478019 2.14368322 4.7275022  4.79858216 3.84491575]
 [3.93165375 4.8016389  4.59106202 2.00029454 2.12915327]]
Answer Q11: 
  [[5.25906164 3.21407548 6.19176174 7.86350532 4.97060904]
 [5.52272639 5.5512401  6.27686569 4.90513468 4.22228806]
 [5.88136541 6.60504564 4.69320741 4.12739045 2.58853358]
 [6.67569649 6.09851199 3.40746819 5.27423954 6.2263545 ]]
Answer Q12: 
  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 

### === Task 2 ===

1. Create a numpy array of size 3 by 4 with random float values between 1 to 5

2. Continuing, print the shape of this array

3. Continuing, access the first row of the array

4. Continuing, access the first column of the array

5. Continuing, access the second row, and third column element

6. Continuing, access the first two columns

7. Continuing, access the  first and third columns using step

8. Continuing, print the whole matrix in reverse columns but not rows

9. Change the third row, fourth column element (i.e., the last element) to 999

In [42]:
#====== 1 =======
n1 = np.random.uniform(1,5,(3,4))
print("Answer Q1: \n ",n1 )
#====== 2 =======
print("Answer Q2: \n ",n1.shape )
#====== 3 =======
print("Answer Q3: \n ",n1[0,:] )
#====== 4 =======
print("Answer Q4: \n ",n1[:,0] )
#====== 5 =======
print("Answer Q5: \n ",n1[1,2] )
#====== 6 =======
print("Answer Q6: \n ",n1[:,:2] )
#====== 7 =======
print("Answer Q7: \n \n ",n1[:,::2] )
#====== 8 =======
print("Answer Q8: \n ",n1[:,::-1] )
#====== 9 =======
n1[2,3] = 999
print("Answer Q9: \n ",n1 )

Answer Q1: 
  [[1.24726909 1.19997352 4.59354111 2.57080785]
 [3.16623633 3.68281867 1.51702308 4.21524162]
 [2.67217978 4.00682201 1.60548286 3.82234176]]
Answer Q2: 
  (3, 4)
Answer Q3: 
  [1.24726909 1.19997352 4.59354111 2.57080785]
Answer Q4: 
  [1.24726909 3.16623633 2.67217978]
Answer Q5: 
  1.5170230785759342
Answer Q6: 
  [[1.24726909 1.19997352]
 [3.16623633 3.68281867]
 [2.67217978 4.00682201]]
Answer Q7: 
 
  [[1.24726909 4.59354111]
 [3.16623633 1.51702308]
 [2.67217978 1.60548286]]
Answer Q8: 
  [[2.57080785 4.59354111 1.19997352 1.24726909]
 [4.21524162 1.51702308 3.68281867 3.16623633]
 [3.82234176 1.60548286 4.00682201 2.67217978]]
Answer Q9: 
  [[  1.24726909   1.19997352   4.59354111   2.57080785]
 [  3.16623633   3.68281867   1.51702308   4.21524162]
 [  2.67217978   4.00682201   1.60548286 999.        ]]


### === Task 3 ===

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5

2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.

3. Continuing, split the first 70% of the 200 rows of X and y and call them <code>X_train</code> and <code>y_train</code>. Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.

4. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, 1)

5. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features

6. Randomly select one row of <code>X_train</code> by using <code>np.random.randint</code> to select the random row and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>

In [7]:
#====== 1 =======
data = np.random.uniform(1,5,(200,4))
print(data.shape)
#====== 2 =======
X = data[:,:3]
print(X.shape)
y = data[:,3]
print(y.shape)
#====== 3 =======
split = int(0.7*200)
X_train = X[:split,:]
X_test = X[split:,:]
y_train = y[:split]
y_test = y[split:]
#====== 4 =======
print("Answer Q4: \n ",X_train.shape,X_test.shape,y_train.shape,y_test.shape)
#====== 5 =======
m = X_train.shape[0]
n = X_train.shape[1]
print("Answer Q5: \n ", m,n)
#====== 6 =======
print("Answer Q6: \n ")
random_idx = np.random.randint(split)
print(random_idx)
X_i = X_train[random_idx]
print(X_i.shape)
X_i = X_i.reshape(1,n)
print(X_i.shape)

(200, 4)
(200, 3)
(200,)
Answer Q4: 
  (140, 3) (60, 3) (140,) (60,)
Answer Q5: 
  140 3
Answer Q6: 
 
82
(3,)
(1, 3)



7. Randomly select 50 contiguous rows from <code>X_train</code> and called it <code>mini_batch_X</code>.  If the index exceeds, simply grab whatever left.

8. Write a for loop that breaks the <code>X_train</code> into 10 equal pieces without overlap, each containing 10\% of row data but all columns, and simply print their shape

9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>

10. Perform a dot product between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>

11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.

12. Calculate the following 
    $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
    For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
    $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

In [8]:
#====== 7 =======
print("Answer Q7: ")
random_idx = np.random.randint(split)
print(random_idx)
mini_batch_X = X_train[random_idx:random_idx+50,:]
print(mini_batch_X.shape)
#====== 8 =======
print("Answer Q8: ")
size = int(X_train.shape[0]/10)
for idx in range(0, X_train.shape[0], size):
    batch = X_train[idx:idx + size]
    print(batch.shape)
#====== 9 =======
print("Answer Q9: ")
n = X_train.shape[1]
theta = np.zeros(n)
print(theta.shape)
#====== 10 =======
print("Answer Q10: ")
yhat = np.dot(X_train,theta)
print(yhat.shape)
#====== 11 =======
print("Answer Q11: ")
y = np.random.uniform(0,1,(yhat.shape[0]))
print(y.shape)
#====== 12 =======
print("Answer Q12: ")
ans = np.sum((y-yhat)**2)/m
print(ans)

Answer Q7: 
38
(50, 3)
Answer Q8: 
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
Answer Q9: 
(3,)
Answer Q10: 
(140,)
Answer Q11: 
(140,)
Answer Q12: 
0.33389266510160126


### === Task 4 ===

1. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1 and call it intercept

2. Create a <code>theta</code> of shape (n + 1, 4), with random values between 0 and 1

3. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>

4. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

$$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

The second value 0.5 will become

exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

In [9]:
#====== 1 =======
print("Answer Q1: ")
intercept = np.ones((X_train.shape[0],1))
print(intercept.shape)
hi = np.concatenate((X_train,intercept),axis=1)
print(hi.shape)
#====== 2 =======
print("Answer Q2: ")
theta = np.random.uniform(0,1,(n+1,4))
print(theta.shape)
#====== 3 =======
print("Answer Q3: ")
hot_encoded_yhat = np.dot(hi,theta)
print(hot_encoded_yhat.shape)
#====== 4 =======
print("Answer Q4: ")
hot_encoded_yhat = np.exp(hot_encoded_yhat) / np.sum(np.exp(hot_encoded_yhat), axis = 1, keepdims=True)
print(hot_encoded_yhat)

Answer Q1: 
(140, 1)
(140, 4)
Answer Q2: 
(4, 4)
Answer Q3: 
(140, 4)
Answer Q4: 
[[0.82411498 0.01644355 0.04070878 0.11873268]
 [0.61324816 0.05525725 0.12406682 0.20742777]
 [0.88930023 0.00520839 0.02028427 0.08520711]
 [0.93097442 0.00688667 0.01039015 0.05174876]
 [0.60205363 0.06375912 0.12568413 0.20850312]
 [0.86156081 0.01404527 0.02644388 0.09795003]
 [0.90078793 0.02094146 0.01719516 0.06107545]
 [0.79959    0.03034678 0.0461991  0.12386411]
 [0.9165493  0.00543635 0.01390745 0.06410689]
 [0.81362711 0.01047167 0.04255022 0.133351  ]
 [0.7865729  0.01096148 0.04967319 0.15279243]
 [0.71759506 0.02339056 0.07660759 0.18240679]
 [0.76474892 0.0491756  0.05707067 0.12900481]
 [0.84687389 0.02718816 0.03339072 0.09254723]
 [0.79035843 0.01734223 0.0527956  0.13950373]
 [0.84712388 0.00834508 0.03131025 0.11322079]
 [0.5648781  0.0372884  0.15422099 0.24361251]
 [0.84927276 0.00556193 0.02984474 0.11532057]
 [0.74424686 0.03087596 0.06809291 0.15678427]
 [0.71161341 0.01632772 0


5. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X_train.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

6. Create a variable called <code>y</code>, containing shape of <code>(X_train.shape[0], )</code> but with random int values from [0, 1, 2, 3]

7. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>

In [9]:
#====== 5 =======
print("Answer Q5: ")
yhat = np.argmax(hot_encoded_yhat, axis = 1)
print(yhat.shape)
print(X_train.shape[0])
#====== 6 =======
print("Answer Q6: ")
y = np.random.randint(0,4,(X_train.shape[0],))
print(y.shape)
#====== 7 =======
print("Answer Q7: ")
n_classes = len(np.unique(y))
print(n_classes)

Answer Q5: 
(140,)
140
Answer Q6: 
(140,)
Answer Q7: 
4


### === Task 5 ===

1. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>

2. Let's practice masking.  Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0


In [11]:
#====== 1 =======
print("Answer Q1: ")
accuracy = len(yhat[yhat == y])/m
print(accuracy)
#====== 2 =======
print("Answer Q2: ")
hot_encoded_y = np.zeros((X_train.shape[0], 4))
for i, c in enumerate(y):
    hot_encoded_y[i,c] = 1
print(hot_encoded_y[0])

Answer Q1: 
0.22857142857142856
Answer Q2: 
[0. 0. 0. 1.]


3. Grab the data from <code>data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)</code>
    - set X to be all columns except last
    - set y to be the last column
    - select X where its corresponding y is 0
    - select X where its corresponding y is 1
    
4. Grab the data from <code>iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
    - set iris_without_headers to all rows except the first row
    - set sepal_length to second column of iris_without_headers
    - set petal_length to fourth column of iris_without_headers
    - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5

In [38]:
#====== 3 =======
print("Answer Q3: ")
data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)
print(data.shape)
X = data[:,:2]
y = data[:,2]
print(X.shape, y.shape)
X_0 = X[y==0]
X_1 = X[y==1]
print(X_0.shape, X_1.shape)
#====== 4 =======
print("Answer Q4: ")
iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)
print(iris.shape)
iris_without_headers = iris[1:,:]
print(iris_without_headers.shape)
sepal_length = iris_without_headers[:,1].astype(float)
petal_length = iris_without_headers[:,3].astype(float)
cond1= sepal_length<5
cond2= petal_length>1.5
print(petal_length.shape)
filtered = iris_without_headers[cond1& cond2]
print(filtered.shape) 

Answer Q3: 
(20, 3)
(20, 2) (20,)
(10, 2) (10, 2)
Answer Q4: 
(101, 6)
(100, 6)
(100,)
(5, 6)
