# 01 - Numpy Solution

### === Task 1 ===

1. Declare a list of 1 to 4 using range()

2. Continuing, create numpy array from this list, with dtype='float32'

3. Create an numpy array of size 3 by 5 using np.zeros

4. Create an numpy array of size 2 by 3 with filled value 1 / 3

5. Create an array of 5 equal-distanced values for 0 to 10

6. Create an array of number for 0.001, 0.01, 0.1, 1 using np.logspace

7. Create a diagonal matrix of list [1, 2, 3, 4]


8. Create a random array of size 4 by 5 all filled with random values between 0 and 1

9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5

10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5

11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution

12. Create an identity matrix of size 5 by 5

In [26]:
import numpy as np

#====== 1 =======
a = list(range(5))
print("Answer Q1: ", a)

#====== 2 =======
arr2 = np.array(a, dtype = 'float32')
print("Answer Q2: ", arr2)

#====== 3 =======
arr3 = np.zeros((3,5)) 
print("Answer Q3: ", arr3)

#====== 4 =======
arr4 = np.full((2,3), 1/3)
print("Answer Q4: \n", arr4)

#====== 5 =======
arr5 = np.linspace(0,10,25)
print("Answer Q5: \n", arr5)

#====== 6 =======
arr6 = np.logspace(-3, 0, 4)
print("Answer Q6: ", arr6)

#====== 7 =======
arr7 = np.diag(np.arange(1,5))
print("Answer Q7: \n", arr7)

#====== 8 =======
arr8 = np.random.random((4,5))
print("Answer Q8: \n", arr8)

#====== 9 =======
arr9 = np.random.randint(2, 5, (4, 5))
print("Answer Q9: \n", arr9)

#====== 10 =======
arr10 = np.random.normal(5, 1, (4, 5))
print("Answer Q10: \n", arr10)

#====== 11 =======
arr11 = np.eye(5)
print("Answer Q11: \n", arr11)

Answer Q1:  [0, 1, 2, 3, 4]
Answer Q2:  [0. 1. 2. 3. 4.]
Answer Q3:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Answer Q4: 
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Answer Q5: 
 [ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]
Answer Q6:  [0.001 0.01  0.1   1.   ]
Answer Q7: 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Answer Q8: 
 [[0.29268184 0.28084109 0.41968982 0.09977518 0.49353083]
 [0.53644826 0.82875682 0.82243325 0.62593286 0.11373274]
 [0.02443321 0.44478503 0.18600105 0.34518823 0.00408593]
 [0.31466676 0.98802185 0.84167037 0.0254148  0.77089309]]
Answer Q9: 
 [[4 3 2 4 4]
 [2 4 2 3 3]
 [4 3 4 2 3]
 [2 2 2 3 3]]
Answer Q10: 
 [[6.25862187 4.67140126 4.74085736 4.5550866  4.2

### === Task 2 ===

1. Create a numpy array of size 3 by 4 with random float values between 1 to 5

2. Continuing, print the shape of this array

3. Continuing, access the first row of the array

4. Continuing, access the first column of the array

5. Continuing, access the second row, and third column element

6. Continuing, access the first two columns

7. Continuing, access the  first and third columns using step

8. Continuing, print the whole matrix in reverse columns but not rows

9. Change the third row, fourth column element (i.e., the last element) to 999

In [38]:
#====== 1 =======
a = np.random.uniform(1, 5, (3, 4))
print("Answer Q1: \n", a)

#====== 2 =======
print("Answer Q2: ", a.shape)

#====== 3 =======
print("Answer Q3: ", a[0])

#====== 4 =======
print("Answer Q4: ", a[:,0])

#====== 5 =======
print("Answer Q5: ", a[1,2])

#====== 6 =======
print("Answer Q6: \n", a[:,:2])

#====== 7 =======
print("Answer Q7: \n", a[:,::2])

#====== 8 =======
print("Answer Q8: \n", a[:,::-1])

#====== 9 =======
a[2,3] = 999
print("Answer Q9: \n", a)

Answer Q1: 
 [[4.48987655 1.63979548 1.33517002 3.07348036]
 [1.8215582  2.67075715 3.72718448 1.08963052]
 [4.39267756 3.74073256 3.03360539 1.90370377]]
Answer Q2:  (3, 4)
Answer Q3:  [4.48987655 1.63979548 1.33517002 3.07348036]
Answer Q4:  [4.48987655 1.8215582  4.39267756]
Answer Q5:  3.72718448221732
Answer Q6: 
 [[4.48987655 1.63979548]
 [1.8215582  2.67075715]
 [4.39267756 3.74073256]]
Answer Q7: 
 [[4.48987655 1.33517002]
 [1.8215582  3.72718448]
 [4.39267756 3.03360539]]
Answer Q8: 
 [[3.07348036 1.33517002 1.63979548 4.48987655]
 [1.08963052 3.72718448 2.67075715 1.8215582 ]
 [1.90370377 3.03360539 3.74073256 4.39267756]]
Answer Q9: 
 [[  4.48987655   1.63979548   1.33517002   3.07348036]
 [  1.8215582    2.67075715   3.72718448   1.08963052]
 [  4.39267756   3.74073256   3.03360539 999.        ]]


### === Task 3 ===

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5 and name it <code>Data</code>

2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.

3. Continuing, split the first 70% of the 200 rows of X and y and call them <code>X_train</code> and <code>y_train</code>. Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.

<img src="../figures/02.07-numpy-Task.png" width=1000 height=1000 />

4. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, 1)

5. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features

6. Randomly select one row of <code>X_train</code> by using <code>np.random.randint</code> to select the random row and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>

7. Randomly select 50 contiguous rows from <code>X_train</code> by using <code>np.random.randint</code> to select a random starting row and called it <code>mini_batch_X</code>.  If the index exceeds, simply grab whatever left.

8. Write a for loop that breaks the <code>X_train</code> row-wise into 10 equal pieces without overlap, and simply print their shape

9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>

10. Perform a **dot product** between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>
Hint: https://www.guru99.com/numpy-dot-product.html

<img src="../figures/02.07-numpy-Task-dot-explained.png" width=800 height=800 />

11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.

12. Calculate the following 
    $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
    For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
    $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

In [86]:
#====== 1 =======
data = np.random.uniform(1,5,(200,4))

#====== 2 =======
X = data[:,:3]
y = data[:,-1]
print("X.shape : ", X.shape)
print("y.shape : ", y.shape)

#====== 3 =======
num_train = int(0.7 * X.shape[0])
X_train = X[:num_train]
y_train = y[:num_train]
X_test = X[num_train:]
y_test = y[num_train:]

#====== 4 =======
print("X_train.shape : ", X_train.shape)
print("y_train.shape : ", y_train.shape)
print("X_test.shape : ", X_test.shape)
print("y_test.shape : ", y_test.shape)

#====== 5 =======
m = X_train.shape[0]
n = X_train.shape[1]

X.shape :  (200, 3)
y.shape :  (200,)
X_train.shape :  (140, 3)
y_train.shape :  (140,)
X_test.shape :  (60, 3)
y_test.shape :  (60,)


In [106]:
#====== 6 =======
X_i = X_train[np.random.randint(0,m,1)]
print("X_i.shape : ", X_i.shape)

#====== 7 =======
start_idx = int(np.random.randint(0,m,1)) 
mini_batch_X = X_train[start_idx:start_idx+50]
print("mini_batch_X.shape : ", mini_batch_X.shape)

#====== 8 =======
for i in range(10):
#     print((200//10) * i)
#     print((200//10) * (i+1))
    X_train_piece = X_train[(140//10) * i:((140//10) * (i+1))]
    print("X_train_piece.shape : ", X_train_piece.shape)
    
#====== 9 =======
theta = np.zeros((n,))
print("theta.shape : ", theta.shape)

#====== 10 =======
yhat = X_train @ theta
print("yhat.shape : ", yhat.shape)

#====== 11 =======
y = np.random.random(yhat.shape)
print("y.shape : ", y.shape)

#====== 12 =======
result = np.sum(np.power((yhat-y),2)) / m
print("result : ", result)

X_i.shape :  (1, 3)
mini_batch_X.shape :  (13, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
X_train_piece.shape :  (14, 3)
theta.shape :  (3,)
yhat.shape :  (140,)
y.shape :  (140,)
result :  0.32287695430420527


### === Task 4 ===

1. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1

2. Create a <code>theta</code> of shape (n + 1, 4), with random values between 0 and 1

3. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>

4. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

$$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

The second value 0.5 will become

exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

5. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

6. Create a variable called <code>y</code>, containing shape of <code>(X_train.shape[0], )</code> but with random int values from [0, 1, 2, 3]

7. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>

In [121]:
#====== 1 =======
ones = np.ones((m,1))
X_train_ones = np.concatenate((X_train, ones), axis = 1)
print("X_train_ones.shape : ", X_train_ones.shape)

#====== 2 =======
theta = np.random.uniform(0, 1, (n+1, 4))
print("theta.shape : ", theta.shape)

#====== 3 =======
hot_encoded_yhat = X_train_ones @ theta
print("hot_encoded_yhat.shape : ", hot_encoded_yhat.shape)

#====== 4 =======
numerator = np.exp(hot_encoded_yhat)
denominator = (np.sum((np.exp(hot_encoded_yhat)),axis = 1)).reshape(denominator.shape[0],1)
print("numerator.shape : ", numerator.shape)
print("denominator.shape : ", denominator.shape)

result = numerator / denominator
print("result.shape : ", result.shape)

#====== 5 =======
yhat = np.argmax(hot_encoded_yhat, axis=1)
print("yhat.shape : ", yhat.shape)

#====== 6 =======
y = np.random.randint(0,4,(X_train.shape[0], ))
print("y : ", y)

#====== 7 =======
n_classes = len(np.unique(y))
print("n_classes : ", n_classes)

X_train_ones.shape :  (140, 4)
theta.shape :  (4, 4)
hot_encoded_yhat.shape :  (140, 4)
numerator.shape :  (140, 4)
denominator.shape :  (140, 1)
result.shape :  (140, 4)
yhat.shape :  (140,)
y :  [3 2 0 0 1 2 1 2 3 3 0 2 1 2 3 2 3 0 2 3 2 3 0 2 2 0 3 1 0 0 3 1 2 3 1 1 1
 2 2 0 3 1 1 1 0 2 2 1 1 3 1 0 2 2 2 1 1 1 2 3 3 3 2 3 2 3 0 3 2 0 2 2 0 1
 3 1 0 0 1 0 0 1 0 2 0 1 2 2 2 2 2 0 1 0 2 2 2 1 2 0 3 0 3 3 2 3 1 1 0 0 3
 0 3 3 3 2 0 2 1 2 3 2 1 2 2 2 1 0 1 0 2 3 1 0 2 2 3 3 1 2]
n_classes :  4


### === Task 5 ===

1. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>

2. Let's practice masking.  Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0

3. Grab the data from <code>data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)</code>
    - set X to be all columns except last
    - set y to be the last column
    - select X where its corresponding y is 0
    - select X where its corresponding y is 1
    
4. Grab the data from <code>iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
    - set iris_without_headers to all rows except the first row
    - set sepal_length to second column of iris_without_headers
    - set petal_length to fourth column of iris_without_headers
    - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5

In [135]:
#====== 1 =======
accuracy = np.sum(yhat==y)/m
print("Accuracy : " ,accuracy)

#====== 2 =======
hot_encoded_y = np.zeros((X_train.shape[0], 4))

for i in range(m):
    for j in range(n_classes):
        if y[i] == j:
            hot_encoded_y[i,j] = 1
        else :
            pass
        
print("hot_encoded_y : \n", hot_encoded_y[:5])

Accuracy :  0.2785714285714286
hot_encoded_y : 
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [144]:
#====== 3 =======
data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)
print(data.shape)

X = data[:,:-1]
print("X.shape : ", X.shape)
y = data[:,-1]
print("y.shape : ", y.shape)

X_0 = X[y==0]
print("X_0.shape : ", X_0.shape)

X_1 = X[y==1]
print("X_1.shape : ", X_1.shape)

(20, 3)
X.shape :  (20, 2)
y.shape :  (20,)
X_0.shape :  (10, 2)
X_1.shape :  (10, 2)


In [4]:
#====== 4 =======
iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)
print("iris.shape : ", iris.shape)

iris_without_headers = iris[1:,:]
print("iris_without_headers.shape : ", iris_without_headers.shape)

sepal_length = iris_without_headers[:,1].astype(float)
print("sepal_length.shape : ", sepal_length.shape)

petal_length = iris_without_headers[:,3].astype(float)
print("petal_length.shape : ", petal_length.shape)

print("Filtered iris : ", iris_without_headers[(sepal_length < 5) & (petal_length > 1.5)].shape)

iris.shape :  (101, 6)
iris_without_headers.shape :  (100, 6)
sepal_length.shape :  (100,)
petal_length.shape :  (100,)
Filtered iris :  (5, 6)
