### === Task 1 ===

1. Declare a list of 1 to 4 using range()

2. Continuing, create numpy array from this list, with dtype='float32'

3. Create an numpy array of size 3 by 5 using np.zeros

4. Create an numpy array of size 2 by 3 with filled value 1 / 3

5. Create a list of 5 numbers for 0 to 10

6. Create a list of number for 0.001, 0.01, 0.1, 1 using np.logspace

7. Create a diagonal matrix of list [1, 2, 3, 4]

8. Create a random array of size 4 by 5 all filled with random values between 0 and 1

9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5

10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5

11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution

12. Create an identity matrix of size 5 by 5

In [1]:
# 1. Declare a list of 1 to 4 using range()
list(range(1, 5))

[1, 2, 3, 4]

In [2]:
# 2. Continuing, create numpy array from this list, with dtype='float32'
import numpy as np
some_numpy = np.array(list(range(1, 5)), dtype='float32')
some_numpy

array([1., 2., 3., 4.], dtype=float32)

In [3]:
# 3. Create an numpy array of size 3 by 5 using np.zeros
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# 4. Create an numpy array of size 2 by 3 with filled value 1 / 3
np.full((2, 3), 1/3)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [5]:
# 5. Create a list of 5 numbers for 0 to 10
np.linspace(0, 10, 5)   #<---i keep as 5 to keep answer short; you can change 5 to 500

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
# 6. Create a list of number for 0.001, 0.01, 0.1, 1 using np.logspace
np.logspace(-3, 0, 4)

array([0.001, 0.01 , 0.1  , 1.   ])

In [7]:
# 7. Create a diagonal matrix of list [1, 2, 3, 4]
np.diag(np.arange(1, 5))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
# 8. Create a random array of size 4 by 5 all filled with random values between 0 and 1
np.random.random((4, 5))

array([[0.60551604, 0.45475097, 0.41386533, 0.79196644, 0.81554505],
       [0.23913011, 0.5433503 , 0.69872384, 0.53139624, 0.6798039 ],
       [0.26870681, 0.88601067, 0.69475738, 0.14268511, 0.36334933],
       [0.47963225, 0.88696358, 0.98347546, 0.73489696, 0.41133622]])

In [9]:
# 9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5
np.random.randint(2, 5, (4, 5))

array([[3, 3, 2, 4, 2],
       [4, 3, 3, 4, 2],
       [3, 2, 4, 2, 3],
       [2, 2, 2, 4, 4]])

In [10]:
# 10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5
np.random.uniform(low=2, high=5, size=(4, 5))

array([[2.9401159 , 2.77813718, 2.76466585, 3.87559998, 3.37903217],
       [2.72652606, 3.00139326, 2.72287969, 4.49237669, 2.63759126],
       [3.08856712, 2.10158294, 4.41870589, 3.25620344, 2.893651  ],
       [3.735789  , 4.74674814, 4.27413259, 3.55354056, 4.95169744]])

In [11]:
# 11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution
np.random.normal(5, 1, (4, 5))

array([[3.32576786, 4.62546138, 4.16731813, 5.53174712, 5.2716294 ],
       [3.65668734, 6.08016332, 5.58964952, 5.21623878, 5.73316718],
       [5.20125187, 5.61724956, 6.24357715, 4.73264344, 5.07906427],
       [5.50345423, 5.39808918, 4.84881801, 3.27200607, 4.60031968]])

In [12]:
# 12. Create an identity matrix of size 5 by 5
np.eye(5)
#np.identity(5) -> equivalent

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### === Task 2 ===

1. Create a numpy array of size 3 by 4 with random float values between 1 to 5

2. Continuing, print the shape of this array

3. Continuing, access the first row of the array

4. Continuing, access the first column of the array

5. Continuing, access the second row, and third column element

6. Continuing, access the first two columns

7. Continuing, access the  first and third columns using step

8. Continuing, print the whole matrix in reverse columns but not rows

9. Change the third row, fourth column element (i.e., the last element) to 999

In [27]:
# 1. Create a numpy array of size 3 by 4 with random float values between 0 to 5
a = np.random.random((3, 4)) * 5

array([[3.02437847, 1.45119725, 2.37633654, 2.51028751],
       [3.38507121, 1.82138563, 2.92293982, 0.38880035],
       [1.85533898, 2.13873813, 4.08223766, 1.55169357]])

In [14]:
# 2. Continuing, print the shape of this array
a.shape

(3, 4)

In [15]:
# 3. Continuing, access the first row of the array
a[:1]

array([[2.60088738, 2.03144109, 3.64735114, 2.37424414]])

In [16]:
# 4. Continuing, access the first column of the array
a[:, :1]

array([[2.60088738],
       [3.98571097],
       [4.51080579]])

In [17]:
# 5. Continuing, access the second row, and third column element
a[1, 2]

1.333067757325943

In [18]:
# 6. Continuing, access the first two columns
a[:, :2]

array([[2.60088738, 2.03144109],
       [3.98571097, 4.88237116],
       [4.51080579, 1.02266738]])

In [19]:
# 7. Continuing, access the  first and third columns using step
a[:, ::2]

array([[2.60088738, 3.64735114],
       [3.98571097, 1.33306776],
       [4.51080579, 3.42679858]])

In [20]:
# 8. Continuing, print the whole matrix in reverse columns but not rows
a[:, ::-1]

array([[2.37424414, 3.64735114, 2.03144109, 2.60088738],
       [2.40008414, 1.33306776, 4.88237116, 3.98571097],
       [1.18149414, 3.42679858, 1.02266738, 4.51080579]])

In [21]:
# 9. Change the third row, fourth column element (i.e., the last element) to 999
a[2, 3] = 999
a

array([[  2.60088738,   2.03144109,   3.64735114,   2.37424414],
       [  3.98571097,   4.88237116,   1.33306776,   2.40008414],
       [  4.51080579,   1.02266738,   3.42679858, 999.        ]])

### === Task 3 ===

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5

2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.

3. Continuing, split the first 70% of the 200 rows of X and y and call them <code>X_train</code> and <code>y_train</code>. Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.

4. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, 1)

5. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features

6. Randomly select one row of <code>X_train</code> by using <code>np.random.randint</code> to select the random row and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>


7. Randomly select 50 contiguous rows from <code>X_train</code> and called it <code>mini_batch_X</code>.  If the index exceeds, simply grab whatever left.

8. Write a for loop that breaks the <code>X_train</code> into 10 equal pieces without overlap, each containing 10\% of row data but all columns, and simply print their shape

9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>

10. Perform a dot product between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>

11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.

12. Calculate the following 
    $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
    For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
    $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

In [16]:
# 1. Create a numpy array of size 200 by 4 with random float values between 1 to 5
a = np.random.uniform(1, 5, (200, 4))
a.shape

(200, 4)

In [17]:
#2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column
X = a[:,:3]
print(X.shape)
y = a[:,3]
print(y.shape)

(200, 3)
(200,)


In [20]:
# 3. Continuing, split the first 70% of the 200 rows of X and y and call them <code>X_train</code> and <code>y_train</code>. Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.
total_size = 200
train_size = int(0.7 * total_size)
test_size = total_size - train_size
X_train = X[:train_size, :]
y_train = y[:train_size]
X_test = X[train_size:,:]
y_test = y[train_size:]

In [21]:
#4. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, 1)
X_train.shape, y_train.shape

((140, 3), (140,))

In [22]:
# 5. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features
m = X_train.shape[0] #number of samples
n = X_train.shape[1] #number of features
print(f"X_train has {m} samples and {n} features")

X_train has 140 samples and 3 features


In [26]:
# 6. Randomly select one row of <code>X_train</code> by using <code>np.random.randint</code> to select the random row and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>
random_index = np.random.randint(train_size)
print(random_index)
X_i = X_train[random_index]
X_i = X_i.reshape(1, -1)
print(X_i.shape)

82
(1, 3)


In [27]:
# 7. Randomly select 50 contiguous rows from <code>X_train</code> and called it <code>mini_batch_X</code>.  If the index exceeds, simply grab whatever left.
random_index = np.random.randint(train_size)
print(random_index)
mini_batch_X = X_train[random_index:random_index+50]
print(mini_batch_X.shape)

58
(50, 3)


In [28]:
# 8. Write a for loop that breaks the <code>X_train</code> into 10 equal pieces without overlap, each containing 10\% of row data but all columns, and simply print their shape
batch_size = int(X_train.shape[0] / 10)
for index in range(0, X_train.shape[0], batch_size):
    batch = X_train[index:index + batch_size]
    print(batch.shape)

(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)


In [29]:
# 9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>
theta = np.zeros(n, )
theta.shape

(3,)

In [30]:
# 10. Perform a dot product between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>
yhat = X_train @ theta  #(140, 3) @ (3, )
yhat.shape

(140,)

In [31]:
# 11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.
y = np.random.uniform(0, 1, yhat.shape)
y.shape

(140,)

In [32]:
# 12. Calculate the following 
#     $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
#     For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
#     $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

m = yhat.shape[0]
(((y - yhat)**2).sum())/m

0.2967378033488936

### === Task 4 ===

1. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1 and call it intercept

2. Create a <code>theta</code> of shape (n + 1, 4), with random values between 0 and 1

3. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>

4. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

$$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

The second value 0.5 will become

exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

5. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

6. Create a variable called <code>y</code>, containing shape of <code>(X_train.shape[0], )</code> but with random int values from [0, 1, 2, 3]

7. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>


In [33]:
# 1. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1
intercept = np.ones((X_train.shape[0], 1))

#concatenate the intercept based on axis=1
X_train = np.concatenate((intercept, X_train), axis=1)

X_train.shape

(140, 4)

In [34]:
# 2. Create a <code>theta</code> of shape (n + 1, 4)
theta = np.random.uniform(0, 1, (n+1, 4))
theta.shape

(4, 4)

In [35]:
# 3. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>
hot_encoded_yhat = X_train @ theta
print(hot_encoded_yhat.shape)

print(hot_encoded_yhat[1])

(140, 4)
[3.69401822 9.28249212 7.16671242 5.15273068]


In [36]:
# 4. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

# $$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

# For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

# exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

# The second value 0.5 will become

# exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

hot_encoded_yhat = np.exp(hot_encoded_yhat) / np.sum(np.exp(hot_encoded_yhat), axis = 1, keepdims=True)

print(hot_encoded_yhat[1])

[0.00328029 0.8769109  0.1057022  0.01410662]


In [37]:
# 5. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

yhat = np.argmax(hot_encoded_yhat, axis=1)
print(yhat.shape)
yhat

(140,)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
# 6. Create a variable called <code>y</code>, containing shape of <code>(X.shape[0], )</code> but with random int values from [0, 1, 2, 3]
y = np.random.randint(4, size = (X_train.shape[0], ))
print(y.shape)
y

(140,)


array([3, 3, 1, 0, 0, 3, 0, 0, 2, 0, 3, 3, 2, 0, 3, 2, 1, 3, 1, 1, 1, 3,
       3, 1, 0, 0, 0, 1, 3, 1, 0, 2, 2, 0, 1, 2, 1, 2, 0, 0, 1, 0, 3, 0,
       3, 0, 3, 1, 1, 2, 2, 3, 1, 0, 1, 3, 0, 3, 3, 2, 3, 1, 1, 1, 3, 1,
       0, 2, 0, 1, 2, 2, 3, 0, 1, 2, 0, 3, 3, 0, 1, 0, 2, 2, 0, 0, 2, 3,
       0, 1, 3, 2, 3, 2, 0, 1, 2, 2, 0, 2, 3, 0, 0, 3, 2, 2, 3, 1, 0, 3,
       3, 2, 2, 0, 2, 2, 1, 3, 0, 1, 0, 3, 2, 3, 0, 1, 0, 3, 0, 2, 2, 0,
       2, 1, 3, 2, 3, 0, 0, 1])

In [39]:
# 7. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>
n_classes = len(np.unique(y))
print(n_classes)

4


### === Task 5 ===

1. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>

2. Let's practice masking.  Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0

3. Grab the data from <code>data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)</code>
    - set X to be all columns except last
    - set y to be the last column
    - select X where its corresponding y is 0
    - select X where its corresponding y is 1
    
4. Grab the data from <code>iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
    - set iris_without_headers to all rows except the first row
    - set sepal_length to second column of iris_without_headers
    - set petal_length to fourth column of iris_without_headers
    - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5

In [40]:
#1. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>
print(yhat == y)
accuracy = ((yhat == y).sum())/m
print(accuracy)

[False False  True False False False False False False False False False
 False False False False  True False  True  True  True False False  True
 False False False  True False  True False False False False  True False
  True False False False  True False False False False False False  True
  True False False False  True False  True False False False False False
 False  True  True  True False  True False False False  True False False
 False False  True False False False False False  True False False False
 False False False False False  True False False False False False  True
 False False False False False False False False False False False  True
 False False False False False False False False  True False False  True
 False False False False False  True False False False False False False
 False  True False False False False False  True]
0.21428571428571427


In [64]:
# 2. Let's practice masking.  Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0
m = X_train.shape[0]  #no.of samples
k = 4 #no. of classes
hot_encoded_y = np.zeros((m, k))
for each_class in range(k):
    cond = y == each_class
    hot_encoded_y[np.where(cond), each_class] = 1
    
hot_encoded_y[0]

(20, 1)
(20, 1)
(20, 1)
(20, 1)


array([1., 1., 0., 0.])

In [77]:
# 3. Grab the data from <code>data = np.genfromtxt('data/perceptron.csv', delimiter=',', skip_header=1)</code>
#     - set X to be all columns except last
#     - set y to be the last column
#     - select X where its corresponding y is 0
#     - select X where its corresponding y is 1
    
data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)
print(data.shape)

X = data[:, :-1]
y = data[:, -1]

cond0 = y == 0
cond1 = y == 1
print("X when y is 0: ", X[cond0, :])
print("X when y is 1: ", X[cond1, :])

(20, 3)
X when y is 0:  [[0.4946 5.7661]
 [1.2888 5.3433]
 [1.4293 4.5592]
 [1.1921 5.8563]
 [1.063  5.7357]
 [1.5079 5.8622]
 [0.2678 6.9931]
 [0.9726 3.6268]
 [2.5389 3.3884]
 [2.473  5.6404]]
X when y is 1:  [[4.7206 5.7661]
 [4.2898 5.3433]
 [4.2286 4.5592]
 [3.1454 5.8563]
 [5.1043 5.7357]
 [3.9799 5.8622]
 [4.5288 6.9931]
 [4.106  3.6268]
 [4.7555 3.3884]
 [4.7977 5.6404]]


In [72]:
# 4. Grab the data from <code>iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
#     - set iris_without_headers to all rows except the first row
#     - set sepal_length to second column of iris_without_headers
#     - set petal_length to fourth column of iris_without_headers
#     - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5

In [82]:
iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)
iris_without_headers = np.array(iris[1:])  #remove first row
sepal_length = iris_without_headers[:, 1].astype(float)
petal_length = iris_without_headers[:, 3].astype(float)
cond1 = petal_length > 1.5
cond2 = sepal_length < 5
filtered_iris = iris_without_headers[cond1 & cond2]
print("Filtered iris: ", filtered_iris.shape)

Filtered iris:  (5, 6)
