# NumPy

- is basically list
- NumPy is much faster and efficient than list
- NumPy also works like vectors, which is suitable of machine learning

## Creation

In [6]:
import numpy as np
np.__version__

'1.23.1'

In [7]:
#first, create your list
a = [1, 2, 3]

#second, use np.array(the list) will create the numpy array
numpy_a = np.array(a)

type(numpy_a)

numpy.ndarray

## how does numpy differ from list

In [8]:
#1.  NumPy only support one data type for one list

#example: list - different types
a = [1, 3.0, True, "Chaky"]

#example: numpy array - one type
numpy_a = np.array(a)  #convert everything to string....
numpy_a

array(['1', '3.0', 'True', 'Chaky'], dtype='<U32')

In [11]:
#example: list - float + int
a = [1, 3.0, 3.2, 9]

#convert this to numpy array
numpy_a = np.array(a)  #everything becomes float
numpy_a.dtype

dtype('float64')

In [ ]:
#why NumPy only support one data type?!
#this is because NumPy wants to be fast and efficient!

In [13]:
#2. NumPy behaves like a vector

#list behaves like some object, NOT vectors
a = [1, 2, 3]
a * 3

#NumPy behaves like a vector
numpy_a = np.array(a) #a vector of 1, 2, 3
numpy_a * 3  #this is basically linear algebra

array([3, 6, 9])

## Selecting and accessing elements

In [14]:
numpy_a = np.arange(5)  #this is basically like python range
numpy_a

array([0, 1, 2, 3, 4])

In [17]:
#same way as list
#format: [start:end:step]  #end is exclusive!

#1. I want to get 2
numpy_a[2]

#2. I want 2 to 4
numpy_a[2:5]

#3. I want 4
numpy_a[-1]

4

In [18]:
#accessing becomes a bit hard, when is multidimensional
numpy_a = np.arange(12).reshape(4, 3)
numpy_a

#here we have a two-dimensional array of shape (4, 3)
#4 rows, and 3 cols

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
numpy_a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
#format of accessing
#format: [row - start:end:step, col - start:end:step]

#1. I want the first row
numpy_a[0, :]

#2. I want the first col
numpy_a[:, 0]

#what if I want 0, 1
#row 0, col 0, 1
numpy_a[0, 0:2]

#numpy as supports list of index like this (called fancy indexing)
numpy_a[0, [0, 1]]


array([0, 1])

In [26]:
numpy_a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#Ex 1:  give me 3, 4, 5

#Ex 2:  give me 10, 11

#Ex 3:  give me 2, 4, 6

#Ex 4:  give me 11, 10, 9

#finish one by one, and put on the chat....