# NumPy

- is basically list
- NumPy is much faster and efficient than list
- NumPy also works like vectors, which is suitable of machine learning

## Creation

In [6]:
import numpy as np
np.__version__

'1.23.1'

In [7]:
#first, create your list
a = [1, 2, 3]

#second, use np.array(the list) will create the numpy array
numpy_a = np.array(a)

type(numpy_a)

numpy.ndarray

## how does numpy differ from list

In [8]:
#1.  NumPy only support one data type for one list

#example: list - different types
a = [1, 3.0, True, "Chaky"]

#example: numpy array - one type
numpy_a = np.array(a)  #convert everything to string....
numpy_a

array(['1', '3.0', 'True', 'Chaky'], dtype='<U32')

In [11]:
#example: list - float + int
a = [1, 3.0, 3.2, 9]

#convert this to numpy array
numpy_a = np.array(a)  #everything becomes float
numpy_a.dtype

dtype('float64')

In [ ]:
#why NumPy only support one data type?!
#this is because NumPy wants to be fast and efficient!

In [13]:
#2. NumPy behaves like a vector

#list behaves like some object, NOT vectors
a = [1, 2, 3]
a * 3

#NumPy behaves like a vector
numpy_a = np.array(a) #a vector of 1, 2, 3
numpy_a * 3  #this is basically linear algebra

array([3, 6, 9])

## Selecting and accessing elements

In [14]:
numpy_a = np.arange(5)  #this is basically like python range
numpy_a

array([0, 1, 2, 3, 4])

In [17]:
#same way as list
#format: [start:end:step]  #end is exclusive!

#1. I want to get 2
numpy_a[2]

#2. I want 2 to 4
numpy_a[2:5]

#3. I want 4
numpy_a[-1]

4

In [18]:
#accessing becomes a bit hard, when is multidimensional
numpy_a = np.arange(12).reshape(4, 3)
numpy_a

#here we have a two-dimensional array of shape (4, 3)
#4 rows, and 3 cols

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
numpy_a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
#format of accessing
#format: [row - start:end:step, col - start:end:step]

#1. I want the first row
numpy_a[0, :]

#2. I want the first col
numpy_a[:, 0]

#what if I want 0, 1
#row 0, col 0, 1
numpy_a[0, 0:2]

#numpy as supports list of index like this (called fancy indexing)
numpy_a[0, [0, 1]]


array([0, 1])

In [26]:
numpy_a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
#Ex 1:  give me 3, 4, 5
numpy_a[1]

#Ex 2:  give me 10, 11
numpy_a[3, -2:]

#Ex 3:  give me 2, 4, 6 - hint: use fancy indexing on both rows and cols
row = [0, 1, 2]
col = [2, 1, 0]
numpy_a[row, col]

#Ex 4:  give me 11, 10, 9
numpy_a[3, [2, 1, 0]] #or numpy_a[3, ::-1]

#finish one by one, and put on the chat....

array([11, 10,  9])

In [32]:
#couple function that may be useful

#shape
numpy_a.shape

#size #e.g., 4 * 3 = 12 ==> number of items
numpy_a.size

#ndim #refers to how many dimension
numpy_a.ndim

2

# Masking
- usually, to retrieve something based on condition, you need
  to use if else, but using masking, you don't have to...

In [33]:
numpy_a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
numpy_a > 4  
#by putting conditions on numpy array, we got a list of indexes of True and False
#we can treat them as fancy indexes

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
cond = numpy_a > 4
numpy_a[cond]  #this process is called masking....it's WONDERFUL
#why, because you don't have to type if/elif....

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
#maybe i want greater than 4, but less than 10
cond1 = numpy_a > 4
cond2 = numpy_a < 10

numpy_a[cond1 & cond2]  #i can use ampersand & to combine unlimited conditions...

array([5, 6, 7, 8, 9])

Masking is A VERY IMPORTANT CONCEPT....it makes data science very very easy and efficient......so please remember them by heart....

In [38]:
#format: np.random.randint(low, high(exlcusive), size=shape)
a = np.random.randint(0, 10, size = (3, 4))
a

array([[2, 3, 2, 6],
       [4, 7, 3, 0],
       [1, 5, 4, 1]])

In [39]:
#Ex1: get all the numbers less than 5
cond = a < 5
a[cond]

#Ex2: get how many numbers are divisible by 3
cond = a % 3 == 0
a[cond]

#Ex3: get numbers that are greater than 2 and also divisible by 2
cond1 = a > 2
cond2 = a % 2 == 0
a[cond1 & cond2]

array([6, 4, 4])

In [41]:
#want to provide some nice function

#np.argwhere
numpy_a = np.random.randint(0, 10, size=(2, 3))
numpy_a

array([[1, 9, 5],
       [6, 9, 8]])

In [43]:
#tells you the index in which meets the criteria
np.argwhere(numpy_a > 4)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [44]:
#where will give separately the row and col indexes
#this is useful for using later on as fancy indexes 
np.where(numpy_a > 4)

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))

In [45]:
numpy_a

array([[1, 9, 5],
       [6, 9, 8]])

In [46]:
#np.any #is there any element greater than 4...
np.any(numpy_a > 4)

True

In [47]:
#if there is any, then there is also all
#does all elements greater than 4....
np.all(numpy_a > 4)

False

In [48]:
#good function is np.mean, max, min, std, etc....but
#beware the axis...

numpy_a

array([[1, 9, 5],
       [6, 9, 8]])

In [51]:
#get the mean, across the row
np.mean(numpy_a, axis=1)

#get the mean, across the col
np.mean(numpy_a, axis=0)

array([3.5, 9. , 6.5])

In [53]:
#Big exercise today
#if you finish, you can go home

#1. Create a numpy array of size 200 by 4 (use randint), and called it "data"
#imagine you have some data of 200 samples, and you got 4 columns of data
#the first columns are features, and the last column is label
data = np.random.randint(0, 10, size=(200, 4))
                         
#2. Split the array into two arrays, X and y, X contains the first 3 columns, 
# and y contains the last column
X = data[:, :3]  #first three cols
y = data[:, -1]  #last col

#3. Further split X into X_train and X_test, in which X_train holds 70% of data, 
# and X_test holds 30% of data;  similarly, split y into y_train and y_test in the 
# same fashion  (don't use sklearn yet.....)
np.random.shuffle(data)
index = int(X.shape[0] * 0.7)  #int(200 * 0.7)
X_train = data[:index, :3]
X_test  = data[index:, :3]

#assert is like a unit test, if it pass, nothing happens
#if it fails, it will stop the program
assert X_train.shape[0] == index
assert X_test.shape[0]  == X.shape[0] - index

y_train = data[:index, -1]
y_test  = data[index:, -1]

assert y_train.shape[0] == index
assert y_test.shape[0]  == X.shape[0] - index

#challenge 3:  randomly pick 70% indexes, not pick using in order....

#please put into the chat; take a break and come back at 15:00...

In [55]:
#Next exercise
#go to google classrom and download iris.csv

#https://classroom.google.com/c/NTM4OTU3MzExMDE4?cjc=73zvhof

data = np.genfromtxt('data/iris.csv', delimiter=",",
                  encoding="utf-8", dtype=None)

In [56]:
#here we got 150 samples, 5 columns
#first four columns are sepal length, sepal width, petal length, petal width
#last column is label, which is class of iris
#Note that the first row is headers....
data.shape

(151, 5)

In [ ]:
#Ex1. Please remove the first row because it's the header

#Ex2. Retrieve sepal length, petal length as a variable from the data

#Ex3. Get how many unique label of species we have

#Ex4. Compute the mean and std of sepal length of each species

#Ex5. Count how many sample have sepal length less than 5, and petal length 
#greater than 1.5

#Ex6. Find correlation between sepal and petal length
'''
from scipy.stats.stats import pearsonr
corr, _ = pearsonr(sepal_length, petal_length)
'''

#Ex7. Create the X_train, X_test, y_train, y_test
#   Help: you can use train_test_split if you want
#         you can also do manually, like just now.....

#Ex8. Simply run from sklearn.linear_models import LogisticRegression
#   .fit
#   .predict
#   Optional: you can use cross_val_score if you want.