# Programming for Data Science and Artificial Intelligence

## Numpy

In [6]:
#numpy is list
#because 
#   1. numpy is faster
#   2. numpy has more built-in functions that facilitate data science

#to start using numpy

#conda install numpy
#pip install numpy

import numpy as np

In [7]:
#create your first list
python_list = [1, 2, 3]

#convert this list to numpy list
numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [8]:
#one theory: one numpy array can only support one type of data

#but python list can support many types of data in one list
my_list = [1, "Hello", True, 1.0]

In [9]:
my_list = [1, 2, 3, 4.5]

np_list = np.array(my_list)

np_list

array([1. , 2. , 3. , 4.5])

In [10]:
#i can of course convert the type using numpyarray.astype()

np_list_int = np_list.astype(int)

np_list_int

array([1, 2, 3, 4])

Accessing and indexing

In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])  #x = np.array(range(1, 9))

In [12]:
#1st way: using index      so how do get 3
x[2]

3

In [13]:
#2nd way - slicing - get more than one members
#format array[start:end:step] --> end is exclusive

x[0:3]

array([1, 2, 3])

In [14]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
#get 3 - 8

#3 ways

##1st way
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [16]:
##2nd way
x[2:]

array([3, 4, 5, 6, 7, 8])

In [17]:
##3rd way - so no
x[2:-1]

array([3, 4, 5, 6, 7])

In [18]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
#get 7, 8 using minus
x[-2:]

array([7, 8])

In [21]:
#3rd way - fancy indexing
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
#sometimes, i want element index 2 and 4
x[2], x[4]

(3, 5)

In [23]:
#put a list of index you wanna access
x[ [2, 4] ]

array([3, 5])

2D arrays

<center><img src="../figures/02.03-numpy-matrix-indexing.png" width=500/></center>

In [24]:
data = [[1, 2], [3, 4], [5, 6]]

np_list = np.array(data)

np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
#format when you are dealing with multi-dimensional array
#array[dim1, dim2, so on.......]

data

[[1, 2], [3, 4], [5, 6]]

In [30]:
np_list[0, 1]

2

In [31]:
#can you guys retrieve 6 for me

np_list[2, 1]

6

In [32]:
#can you guys get [3, 4], [5, 6]

# np_list[firstdim, secondim]

#1st way: slicing
np_list[ 1: , :]  #if you put [1:3, :]

array([[3, 4],
       [5, 6]])

In [33]:
data

[[1, 2], [3, 4], [5, 6]]

In [34]:
#2nd way: fancy indexing
np_list[ [1, 2] , : ]

array([[3, 4],
       [5, 6]])

In [35]:
#3rd way: the last two

np_list[-2: , :]

array([[3, 4],
       [5, 6]])

In [36]:
data

[[1, 2], [3, 4], [5, 6]]

In [37]:
#chaky, how do i know which dimension is which
np_list[0, ]

array([1, 2])

In [41]:
np_list[: , 0]

array([1, 3, 5])

In [42]:
data

[[1, 2], [3, 4], [5, 6]]

In [48]:
#get 1, 3
np_list[0:2, 0]

#get 1, 5

#1st way: fancy indexing
np_list[   [0, 2] , 0    ]

array([1, 5])

In [49]:
#2nd way: recall the format start:end:step

np_list[           0::2  , 0       ]

array([1, 5])

17:50 - 18:00

In [59]:
x = [
    
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
    
]

np_list = np.array(x)

#1:  get 2, 6, 10, 14
np_list[:, 1]

#2:  get 7, 11
np_list[1:3, 2]

#3:  get 4, 7, 10   - hint: use fancy indexing on both dimensions
np_list[ [0, 1, 2] , [3, 2, 1]]

#4:  get 16, 15, 14, 13  - hint: use step -1

np_list[-1, -1::-1]

array([16, 15, 14, 13])

In [ ]:
#fun exercise you can do at home :-):

#given a matrix = [ [99, 99, 99], 
#                   [99, 99, 99], 
#                   [99, 99, 99]]

#imagine 99 is empty
#assume 1 is X
#assume 0 is O

#get the input from the X side and O side alternatively
#give you a tupe of index

#if X side input (0, 0)
#then the matrix becomes 

#                 [ [X, 99, 99], 
#                   [99, 99, 99], 
#                   [99, 99, 99]]

#if O side input also (0, 0)
#alert them to input again
#otherwise, fill the matrix

#challenge (optional): if the first one to get three in row, stop the game

<center><img src="../figures/02.01-numpy-dimension.png" width=500 /></center>

<center><img src="../figures/02.02-numpy-array-slice.png" width=500 /></center>

<center><img src="../figures/02.04-np_reshape.png" width=500/></center>

<img src="../figures/02.07-numpy-Task.png" width=1000 />


<center><img src="../figures/02.07-numpy-Task-dot-explained.png" width=500 height=500 /></center>

<center><img src="../figures/numpy-axis.jpg" width=500/></center>

<center><img src="../figures/02.06-numpy-concatenate.png" width=500 height=500 /></center>

<center><img src="../figures/numpy-hstack.png" width=200 height=200 /><img src="../figures/numpy-vstack.png" width=120 height=200 /></center>

<center><img src="../figures/numpy-vectorization.png" width=300 height=300 /></center>

<center><img src="../figures/02.05-broadcasting.png" width=400 height=400 /></center>